# Book settings
title: Introduction to Statistics
author: Jacob Frias Koehler, PhD
logo: hennessy.png

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/jfkoehler/statsbook 